### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by splattner** [vshn/k8up#43]
I created the following Schedule:

```
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: backup-netbox
spec:
  archive:
    schedule: '0 0 1 * *'
  backup:
    schedule: '*/5 * * * *'
    keepJobs: 6
  check:
    schedule: '0 1 * * 1'
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14
```

and then a Deployment with a Pod and the following Annotation:

`
appuio.ch/backupcommand: PGPASSWORD=$(cat /etc/secrets/stolon-stolonsupg_su_password) pg_dump -h stolon-proxy -U $(cat /etc/secrets/stolon-stolonsupg_su_username) -d netbox
`

All PVC's in the Namespace have `appuio.ch/backup: "false"` 

and then the Operator crashes:

```
2019/05/22 15:14:14 [INFO] Registering prune schedule backup-netbox in namespace netbox

2019/05/22 15:14:14 [INFO] Registering check schedule backup-netbox in namespace netbox

2019/05/22 15:14:14 [INFO] Registering backup schedule backup-netbox in namespace netbox

E0522 15:14:14.010293 1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51

/usr/local/go/src/runtime/asm_amd64.s:522

/usr/local/go/src/runtime/panic.go:513

/usr/local/go/src/runtime/panic.go:82

/usr/local/go/src/runtime/signal_unix.go:390

/go/src/github.com/vshn/k8up/service/schedule/scheduleRunner.go:225

/go/src/github.com/vshn/k8up/service/schedule/scheduler.go:59

/go/src/github.com/vshn/k8up/operator/handler.go:29

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:305

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:279

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:248

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:224

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:208

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:208

/usr/local/go/src/runtime/asm_amd64.s:1333

panic: runtime error: invalid memory address or nil pointer dereference [recovered]

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfb3047]

goroutine 192 [running]:

github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108

panic(0x1123fa0, 0x1e02a20)

/usr/local/go/src/runtime/panic.go:513 +0x1b9

github.com/vshn/k8up/service/schedule.(*scheduleRunner).Start(0xc00074e1e0, 0x10c2900, 0xc0002a0ae0)

/go/src/github.com/vshn/k8up/service/schedule/scheduleRunner.go:225 +0x877

github.com/vshn/k8up/service/schedule.(*Schedule).Ensure(0xc00036ff80, 0x13cb0a0, 0xc0000b65a0, 0x4, 0x4)

/go/src/github.com/vshn/k8up/service/schedule/scheduler.go:59 +0x381

github.com/vshn/k8up/operator.(*handler).Add(0xc0003ae800, 0x13e0600, 0xc0002f6180, 0x13cb0a0, 0xc0000b65a0, 0x13f2b40, 0x1e37598)

/go/src/github.com/vshn/k8up/operator/handler.go:29 +0x47

github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).handleAdd(0xc0003de210, 0x13e0600, 0xc0002f6180, 0xc0003c0620, 0x14, 0x13cb0a0, 0xc0000b65a0, 0x0, 0x0)

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:305 +0x4b1

github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).processJob(0xc0003de210, 0x13e0600, 0xc0002f6150, 0xc0003c0620, 0x14, 0xc0002f6150, 0x13f2b40)

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:279 +0xf7

github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).getAndProcessNextJob(0xc0003de210, 0xc0001ac500)

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:248 +0x21a

github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).runWorker(0xc0003de210)

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:224 +0x2b

github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).runWorker-fm()

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:208 +0x2a

github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00005d7b0)

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54

github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a11fb0, 0x3b9aca00, 0x0, 0x1, 0xc00003e900)

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe

github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00005d7b0, 0x3b9aca00, 0xc00003e900)

/go/src/github.com/vshn/k8up/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d

github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).run.func1(0xc0003de210, 0xc00003e900)

/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:208 +0x5c

created by github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller.(*generic).run

	/go/src/github.com/vshn/k8up/vendor/github.com/spotahome/kooper/operator/controller/generic.go:207 +0x1e1
```

not yet sure, if I'm just missing anything in the Schedule CRD, but I guess the Operator should be more robust.

the Operator runs with the following ENV's

```
    - name: BACKUP_IMAGE
      value: docker.io/vshn/wrestic:v0.0.10
    - name: BACKUP_GLOBALS3ENDPOINT
      value: https://objects.cloudscale.ch
    - name: BACKUP_GLOBALS3BUCKET
      value: k8up_backup
    - name: BACKUP_GLOBALACCESSKEYID
      value: ....
    - name: BACKUP_GLOBALSECRETACCESSKEY
      value: ....
    - name: BACKUP_GLOBALREPOPASSWORD
      value: ....
    - name: BACKUP_GLOBALRESTORES3ENDPOINT
      value: https://objects.cloudscale.ch
    - name: BACKUP_GLOBALRESTORES3BUCKET
      value: k8up_restore
    - name: BACKUP_GLOBALRESTORES3ACCESKEYID
      value: ...
    - name: BACKUP_GLOBALRESTORES3SECRETACCESSKEY
      value: ...
```

**Comment by Kidswiss** [comment]
Hi @splattner 

Thanks for trying out the K8up operator and pointing out the issue. The problem is within the the `archive` hash in your configuration. Archive is quite a special job that needs slightly different configuration: https://vshn.github.io/k8up/object-specifications/#archive. You should be able to omit the backend settings. But the `restoreMethod` is required.

Of course it's bad, that the operator crashes on this. The whole schedule evaluation needs some more love currently as it will just crash if there are missing settings.

**Comment by splattner** [comment]
thx for the hint, I'll give it a try next Week :) 

cheers
